language: node_js
node_js:
 - "7"
 - "6"
 - "5.1"
before_script:
 - npm install grunt-cli -g
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 5
script:
- grunt
- npm run test:unit
cache:
 directories:
  - node_modules
